name: Upload Datasets

on:
  workflow_dispatch:
  schedule:
    - cron: "15 2 1 */2 *"

env:
  dataset_download_address: "https://dataset.prophesee.ai/index.php/s/ozjYOAAKTUshudQ/download"

jobs:
  get_artifacts:
    name: Get Datasets (Bloated with ML)
    runs-on: ubuntu-latest
    steps:

    - name : Downloading datasets
      timeout-minutes: 10
      run: |
        curl -L -o datasets.zip $dataset_download_address
        unzip datasets.zip

    - name : Uploading datasets to storage
      uses: actions/upload-artifact@master
      with:
        name: datasets #once they have the proper datasets and not this mass, remove the !datasets folders
        path: |
          datasets
          !datasets/metavision_ml
          !datasets/calibration*
          !datasets/jet_monitoring_test
          !datasets/focus.raw

    - name: Slack Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.OPENEB_GITHUB_PROPHESEE_SLACK_WEBHOOK }}
        SLACK_TITLE: Datasets update
        SLACK_MESSAGE: 'Status: ${{ job.status }}'
        SLACK_COLOR: ${{ job.status }}
        SLACK_FOOTER: ""
        MSG_MINIMAL: true
